tiling:
  tile_size: 128
  stride: 128

predictions:
  storage: direct # how the predictions are stored, options: [direct, file_system, rescaled]
  rescale_factor: 0.5 # factor by which data is downscaled in case of "rescaled" storage

post_processing:
  normalization: joined_image # on what level we normalize, options: [individual_tile, joined_image, none]
  smooth_joins:
    apply: True # if this is applied, area around tile joins are is smoothed
    sigma: 2 # sigma of gaussian filter used to smooth this area
    width: 0.1 # width factor, multiplied by tile dimension gives the region width around join which will be smoothed

# overrides metrics from model config
metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    stage: joined_image # stage at which we apply threshold, options: [individual_tile, joined_image]
    method: adaptive # options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

# overrides visualization from model config
visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]
