tiling:
  tile_size: setupInCode
  stride: setupInCode

predictions:
  storage: memory # how the predictions are stored, options: [memory, file_system, memory_downscaled]
  downscale_factor: 0.5 # factor by which data is downscaled in case of "memory_downscaled" storage

post_processing:
  normalization: image # on what level we normalize, options: [tile, image, none]
  smooth_joins:
    apply: True # if this is applied, area around tile joins are is smoothed
    sigma: 2 # sigma of gaussian filter used to smooth this area
    width: 0.1 # width factor, multiplied by tile dimension gives the region width around join which will be smoothed

# overrides metrics from model config
metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
    - AUPRO
    - PRO
  threshold:
    stage: image # stage at which we apply threshold, options: [tile, image]
    method: adaptive # options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

# overrides visualization from model config
visualization:
  show_images: False # show images on the screen
  save_images: setupInCode # save images to the file system
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]
